with-expecter: false
packages:
    github.com/jsfelipearaujo/lambda-register/src/providers/interfaces:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./src/providers/interfaces/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Provider)"